#!/bin/bash
# Last version: 23.04.2015 22:30

echo
echo "Header: ColourTracking.hpp"
echo "Compiling files:"
echo "main.cpp"
echo "ColourTracking.cpp"
echo
echo "Linking libraries:"
echo "opencv_videoio"
echo "opencv_core"
echo "opencv_highgui"
echo "opencv_imgproc"
echo "opencv_imgcodecs"
echo
echo "Starting.."
echo

#start=`date +%s`
if g++ -Wall -std=c++0x main.cpp ColourTracking.cpp -o cam -lopencv_videoio -lopencv_core  -lopencv_highgui -lopencv_imgproc -lopencv_imgcodecs; then
   echo "Compilation succeeded!";
   echo "Output file: cam";
   #end=`date +%s`
   #runtime=$((end-start))
   #echo "Time spent: $runtime";
else
   echo "Compilation failed!";
fi
